#! /usr/bin/env node

import web3 from './config/web3'
import { db, sql } from './config/db'

const FROM_BLOCK = web3.utils.toHex(5027000)
const TO_BLOCK   = web3.utils.toHex(5037550)

const abi = require('./abi/tub.json').abi
const adr = require('./addresses.json')
const tub = new web3.eth.Contract(abi, adr.ethlive.tub)

const options = {
  fromBlock: FROM_BLOCK,
  toBlock:   TO_BLOCK,
}

const insertCup = sql('insertCup.sql')

tub.getPastEvents('LogNewCup', options)
.then(logs => {
  logs.forEach(log => {
    web3.eth.getBlock(log.blockNumber).then(block => {
      let cup = {
        id: web3.utils.hexToNumber(log.returnValues.cup),
        lad: log.returnValues.lad,
        ink: 0,
        art: 0,
        ire: 0,
        block: log.blockNumber,
        timestamp: block.timestamp,
        txHash: log.transactionHash,
        action: 'open'
      }
      db.none(insertCup, {cup: cup}).then(() => {
        console.log(cup);
      });
    });
  });
});
