#!/usr/bin/env node

const lib = require('./lib/common');
const abi = require('./abi/tub.json').abi;
const tub = new lib.web3.eth.Contract(abi, lib.config.addresses.tub);

tub.getPastEvents('LogNewCup', lib.options).then(logs => {
  logs.forEach(log => { insertCup(log) });
});

async function insertCup(log) {
  let data = {
    id: lib.web3.utils.hexToNumber(log.returnValues.cup),
    lad: log.returnValues.lad,
    ink: 0,
    art: 0,
    ire: 0,
    act: 'open',
    arg: null,
    block: log.blockNumber,
    time: await lib.util.timestamp(log.blockNumber),
    tx: log.transactionHash
  }
  lib.db.none(lib.sql.insertCup, { cup: data }).then(() => {
    console.log(data);
  });
}
