#! /usr/bin/env node

import web3 from './config/web3'
import {db,sql} from './config/db'
import {wad,getCupAt} from './utils'

const abi = require('./abi/tub.json').abi
const adr = require('./addresses.json').ethlive.tub;
const tub = new web3.eth.Contract(abi, adr);
const actions = require('./actions.js');

const insertCup = sql('insertCup.sql')

const options = {
  // fromBlock: web3.utils.toHex(4753930),
  // toBlock: 'latest',
  fromBlock: web3.utils.toHex(4903930),
  toBlock: web3.utils.toHex(4933930),
  filter: { sig: actions.sigs }
}

tub.getPastEvents('LogNote', options)
.then(logs => {
  logs.forEach(log => {
    web3.eth.getBlock(log.blockNumber).then(block => {
      getCupAt(log.returnValues.foo, log.blockNumber).then(rtn => {
        let cup = {
          id: web3.utils.hexToNumber(log.returnValues.foo),
          lad: rtn.lad,
          ink: rtn.ink,
          art: rtn.art,
          ire: rtn.ire,
          block: log.blockNumber,
          time: block.timestamp,
          tx: log.transactionHash,
          act: actions.acts[log.returnValues.sig],
          arg: wad('0x'+log.returnValues.bar.substring(26))
        }
        db.none(insertCup, {cup: cup}).then(() => {
          console.log(cup);
        });
      })
    });
  });
});

tub.getPastEvents('LogNewCup', options)
.then(logs => {
  logs.forEach(log => {
    web3.eth.getBlock(log.blockNumber).then(block => {
      let cup = {
        id: web3.utils.hexToNumber(log.returnValues.cup),
        lad: log.returnValues.lad,
        ink: 0,
        art: 0,
        ire: 0,
        block: log.blockNumber,
        time: block.timestamp,
        tx: log.transactionHash,
        act: 'open',
        arg: null
      }
      db.none(insertCup, {cup: cup}).then(() => {
        console.log(cup);
      });
    });
  });
});
