#!/usr/bin/env node

const lib = require('./lib/common');
const abi = require('./abi/med.json');
const med = new lib.web3.eth.Contract(abi, lib.config.addresses.med);

med.getPastEvents('allEvents', lib.options).then(logs => {
  logs.forEach(log => {
    med.methods.peek().call({}, log.blockNumber).then(val => {
      insertPip(log, lib.util.wad(val[0]));
    });
  });
});

async function insertPip(log, val) {
  let data = {
    block: log.blockNumber,
    time: await lib.util.timestamp(log.blockNumber),
    val: val
  }
  lib.db.none(lib.sql.insertPip, data).then(() => {
    console.log('Pip: ', data);
  });
}
